---
Resources:
  # Security Group
  MySecurityGroupSSH:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permitir  Acceso SSH en el puerto 22 
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
  # Instancia EC2
  MyEc2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-09e67e426f25ce0d7
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref MySecurityGroupSSH
  # Elastic IP
  MyElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref MyEc2Instance
